# Generated by Django 5.1.5 on 2025-09-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Konkurs nomi"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Boshlanish sanasi")),
                ("end_date", models.DateTimeField(verbose_name="Tugash sanasi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
            ],
            options={
                "verbose_name": "Konkurs",
                "verbose_name_plural": "Konkurslar",
            },
        ),
        migrations.CreateModel(
            name="ContestCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("subscribe_channel", "Kanalga obuna bo‘lish"),
                            (
                                "invite_users",
                                "Ma’lum miqdorda foydalanuvchi taklif qilish",
                            ),
                            ("bot_start", "Boshqa botga /start bosish"),
                            ("site_register", "Saytda ro‘yxatdan o‘tish"),
                            ("site_activity", "Saytda faol bo‘lish"),
                        ],
                        max_length=50,
                        verbose_name="Shart turi",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Shartga qarab: kanal username/link, talab qilingan user soni, bot username, faollik muddati (kunlarda) va hokazo",
                        max_length=255,
                        null=True,
                        verbose_name="Qiymat",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Majburiymi?"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="Bot.contest",
                        verbose_name="Konkurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konkurs sharti",
                "verbose_name_plural": "Konkurs shartlari",
            },
        ),
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ishtirokchi qo‘shilgan sana"
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="Bot.contest",
                        verbose_name="Konkurs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contests",
                        to="Bot.telegramuser",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konkurs ishtirokchisi",
                "verbose_name_plural": "Konkurs ishtirokchilari",
                "unique_together": {("contest", "user")},
            },
        ),
        migrations.CreateModel(
            name="ConditionCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Bajarildimi?"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tekshirilgan vaqt"
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="Bot.contestcondition",
                        verbose_name="Shart",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_checks",
                        to="Bot.contestparticipant",
                        verbose_name="Ishtirokchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shart bajarilishi",
                "verbose_name_plural": "Shartlar bajarilishi",
                "unique_together": {("participant", "condition")},
            },
        ),
    ]
