# Generated by Django 5.1.5 on 2025-09-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0002_contest_contestcondition_contestparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ishtirokchi tartib raqami"
            ),
        ),
    ]
