# Generated by Django 5.1.5 on 2025-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0003_contestparticipant_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="ref_score",
            field=models.IntegerField(default=0, verbose_name="Referral Ball"),
        ),
    ]
